FROM python:3.9

WORKDIR /usr/src/app

RUN apt-get update && apt-get install unzip -y

RUN pip install mysql-connector-python && \
    pip install pandas && \
    pip install SQLAlchemy && \
    pip install hvplot && \
    pip install panel && \
    pip install matplotlib && \
    pip install numpy && \
    pip install scipy && \
    pip install ipympl && \
    pip install ipykernel && \
    pip install ipywidgets_bokeh && \
    pip install cartopy && \
    pip install vizent --pre

COPY app.py /usr/src/app/app.py
COPY mapbox-logo-black.png /usr/src/app/mapbox-logo-black.png

